nightowlsigns/Controllers/ScheduleImageController.cs
using nightowlsign.data.Models.Image;
using nightowlsign.data.Models.Schedule;
using nightowlsign.data.Models.ScheduleImage;
using System.Collections.Generic;
using System.Web.Mvc;
using nightowlsign.data.Models.UpLoadLog;

namespace nightowlsign.Controllers
{
    public class ScheduleImageController : Controller
    {
        private readonly IScheduleImageManager _scheduleImageManager ;
        private readonly IScheduleManager _scheduleManager;
        private readonly IUpLoadLoggingManager _upLoadLoggingManager;

        public ScheduleImageController(IScheduleImageManager scheduleImageManager, IScheduleManager scheduleManager, IUpLoadLoggingManager upLoadLoggingManager)
        {
            _scheduleImageManager = scheduleImageManager;
            _scheduleManager = scheduleManager;
            _upLoadLoggingManager = upLoadLoggingManager;
        }

        // GET: 
        [Authorize(Roles = "Admin,SuperUser")]
        public ActionResult Index(int signId, int scheduleId, string scheduleName)
        {
            var ssvm = new ScheduleImageViewModel
            {
                SignId = signId,
                Schedule =
                {
                    Id = scheduleId,
                    Name = scheduleName
                }
            };
            ssvm.LoadData();
            return View(ssvm);
        }

        [Authorize(Roles = "Admin,SuperUser")]
        public ActionResult Display(int scheduleId, string scheduleName)
        {

            var ssvm = new ScheduleImageViewModel
            {
                Schedule =
                {
                    Id = scheduleId,
                    Name = scheduleName
                }
            };
            ssvm.GetImagesForThisSchedule(scheduleId);
            return PartialView(ssvm);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,SuperUser")]
        public ActionResult Index(ScheduleImageViewModel model)
        {
            IEnumerable<ImageSelect> imageSelects = model.AllImages;
            //    List<ImageSelect> 
            foreach (var imageSelect in imageSelects)
            {
                _scheduleImageManager.UpdateImageList(imageSelect, model.Schedule);
            }
            _scheduleManager.UpdateDate(model.Schedule.Id);
           _upLoadLoggingManager.Delete(model.Schedule.Id);

            return RedirectToAction("Index", "Schedules", new {SignId=model.SignId});
        }
    }
}

nightowlsigns/Views/ScheduleImage/Display.cshtml
@using nightowlsign.data.Models.ScheduleImage
@model ScheduleImageViewModel

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title" id="modal-title">@Model.Schedule.Name</h4>
</div>
<div class="modal-body">
    <div class="row">
        @foreach (var item in Model.AllImages)
        {
            string imageBase64 = Convert.ToBase64String(item.ThumbNail);
            string imageSrc = $"data:image/gif;base64,{imageBase64}";
            <div class="col-sm-6 col-md-3">
                <img class="img-responsive modal-img" src="@imageSrc" style="width: 100%;">
            </div>
        }
    </div>
</div>

nightowlsigns/Views/ScheduleImage/Index.cshtml
@using nightowlsign.data.Models.ScheduleImage
@model ScheduleImageViewModel

@{
    ViewBag.Title = "Image List";
}

<h2>Image List - @Model.Schedule.Name</h2>

@using (Html.BeginForm("Index", "ScheduleImage", new { SignId = Model.SignId }, FormMethod.Post, new { encType = "multipart/form-data", name = "myform" }))
{
    <!-- Start Hidden form -->
    @Html.HiddenFor(m => m.EventCommand)
    @Html.HiddenFor(m => m.EventArgument)
    @Html.HiddenFor(m => m.Mode)
    @Html.HiddenFor(m => m.Schedule.Id)
    @Html.HiddenFor(m => m.Schedule.Name)
    @Html.HiddenFor(m => m.Schedule.SignId)
    <!-- End Hidden form-->
    <div class="container">
        <div class="row">
            @Html.EditorFor(model => model.AllImages)
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <button type="submit" name="operation" class="btn btn-primary" id="btnSave">
                <i class="glyphicon glyphicon-floppy-disk"></i>&nbsp; Save
            </button>
            <a href="@Url.Action("Index", "Schedules", new { SignId = Model.SignId } )" class="btn btn-primary">
                <i class="glyphicon glyphicon-remove-circle"></i>&nbsp;Cancel
            </a>
        </div>
    </div>
            <!-- End Detail Area-->
}


<script type="text/javascript">
    $(document).ready(function () {

        $("[rel='tooltip']").tooltip();

        $('.caption-over').hover(

        function () {
            $(this).find('.caption-over').slideDown(250);
        },

        function () {
            $(this).find('.caption-over').slideUp(250);
        });
    });
</script>