nightowlsigns/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using nightowlsign.data.Models.Schedule;
using nightowlsign.Models;

namespace nightowlsign.Controllers
{
    public class SchedulesController : Controller
    {
        private readonly IScheduleViewModel _scheduleViewModel;
         public SchedulesController(IScheduleViewModel scheduleViewModel)
        {
            _scheduleViewModel = scheduleViewModel;
                 }
        // GET: 
        [Authorize(Roles = "Admin,SuperUser")]
        public ActionResult Index(int signId)
        {
            signId = Helper.GetSetSignSize(signId);

            _scheduleViewModel.SearchEntity.SignId = signId;
            _scheduleViewModel.HandleRequest();
            return View(_scheduleViewModel);
        }

        [Authorize(Roles = "Admin,SuperUser")]
        public ActionResult Show()
        {
             _scheduleViewModel.HandleRequest();
            return View(_scheduleViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,SuperUser")]
        public ActionResult Index(ScheduleViewModel svm)
        {
            svm.SearchEntity.SignId = Helper.GetSetSignSize(svm.SearchEntity.SignId);

            svm.IsValid = ModelState.IsValid;
            svm.HandleRequest();

            if (svm.IsValid)
            {
                ModelState.Clear();
            }
            else
            {
                foreach (var item in svm.ValidationErrors)
                {
                    ModelState.AddModelError(item.Key, item.Value);
                }
            }
            return View(svm);
        }
    }
}

nightowlsigns/Controllers/SendToSignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using nightowlsign.data.Models;
using ImageProcessor.Services;

namespace nightowlsign.Controllers
{
    public class SendToSignController : Controller
    {
        [Authorize(Roles = "Admin")]
        public ActionResult Index(int scheduleId, string scheduleName)
        {
            SendToSignViewModel ssvm = new SendToSignViewModel();
            ssvm.Schedule.Id = scheduleId;
            ssvm.Schedule.Name = scheduleName;
            ssvm.loadData();
            return View(ssvm);
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Index(SendToSignViewModel svm)
        {
            svm.IsValid = ModelState.IsValid;
            try
            {
                CreateFilesToSend createFilesToSend = new CreateFilesToSend(svm.SignsForSchedule, svm.AllImagesInSchedule, svm.Schedule.Name);
                var playBillFileName = createFilesToSend.PlaybillFileName;
                SendCommunicator sendCommunicator = new SendCommunicator();

                svm.DisplayMessage += sendCommunicator.SendFiletoSign(svm.StoresForSchedule);
                svm.DebugMessage = createFilesToSend.DebugString;
            }
            catch (Exception ex)
            {
                svm.DisplayMessage = ex.ToString();
            }
            svm.loadData();

            return View(svm);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Resend(int scheduleId, string scheduleName)
        {
            SendToSignViewModel ssvm = new SendToSignViewModel();
            ssvm.Schedule.Id = scheduleId;
            ssvm.Schedule.Name = scheduleName;
            ssvm.loadData();
            try
            {
                SendCommunicator sendCommunicator = new SendCommunicator();
                ssvm.DisplayMessage += sendCommunicator.SendFiletoSign(ssvm.StoresForSchedule);
            }
            catch (Exception ex)
            {
                ssvm.DisplayMessage = ex.ToString();
            }
 
            return View("Index",ssvm);
        }
    }
}

nightowlsigns/Views/SendToSign/Index.cshtml
@model nightowlsign.data.Models.SendToSignViewModel


@{
    ViewBag.Title = "Send Images to Signs";
}


@using (Html.BeginForm())
{
    <!-- Start Hidden form -->
    @Html.HiddenFor(m => m.EventCommand)
    @Html.HiddenFor(m => m.EventArgument)
    @Html.HiddenFor(m => m.Mode)
    @Html.HiddenFor(m => m.Schedule.Id)
    @Html.HiddenFor(m => m.Schedule.Name)
    for (int i = 0; i < Model.SignsForSchedule.Count; i++)
    {
        @Html.HiddenFor(model => Model.SignsForSchedule[i].Id)
        @Html.HiddenFor(model => Model.SignsForSchedule[i].Width)
        @Html.HiddenFor(model => Model.SignsForSchedule[i].Height)
        @Html.HiddenFor(model => Model.SignsForSchedule[i].Model)
    }
    for (int i = 0; i < Model.StoresForSchedule.Count; i++)
    {
        @Html.HiddenFor(model => Model.StoresForSchedule[i].Id)
        @Html.HiddenFor(model => Model.StoresForSchedule[i].IPAddress)
        @Html.HiddenFor(model => Model.StoresForSchedule[i].SubMask)
        @Html.HiddenFor(model => Model.StoresForSchedule[i].Port)
        @Html.HiddenFor(model => Model.StoresForSchedule[i].StoreName)
        @Html.HiddenFor(model => Model.StoresForSchedule[i].StoreId)
    }
   <!-- End Hidden form-->

    <div class="row">
        <div class="col-sm-12">
            @if (Model.DisplayMessage.Length>0)
            {
                <div class="alert alert-danger alert-dismissable" role="alert">
                    <button type="button" class="close" data-dissmiss="alert">
                        <span aria-hidden="true">&times</span>

                        <span class="sr-only">Close</span>
                    </button>
                    @Html.DisplayFor(m => m.DisplayMessage)
                    @Html.DisplayFor(m => m.DebugMessage)
                </div>
            }
        </div>
    </div>


    <div class="table-responsive">
        <table class="table table-condensed table-bordered table-striped table-hover">
            <thead>
                <tr>
                    <th>Image</th>
                </tr>
            </thead>
            <tbody>
                @Html.EditorFor(model => model.AllImagesInSchedule)
            </tbody>
        </table>

    </div>
    <div class="row">
        <div class="col-sm-12">
            <button type="submit" name="operation" class="btn btn-primary" id="btnSave">
                <i class="glyphicon glyphicon-floppy-disk"></i>&nbsp;Create & Send
            </button>
            <a href="@Url.Action("Resend", "SendToSign", new { scheduleId=Model.Schedule.Id, scheduleName=Model.Schedule.Name })" class="btn btn-primary">
                <i class="glyphicon glyphicon-repeat"></i>&nbsp;Resend
            </a>
            <a href="@Url.Action("Index", "Schedules")" class="btn btn-primary">
                <i class="glyphicon glyphicon-remove-circle"></i>&nbsp;Cancel
            </a>
        </div>
    </div>



}

nightowlsigns/Views/SendToSign/Resend.cshtml
@model nightowlsign.data.Models.SendToSignViewModel

@{
    ViewBag.Title = "Send Images to Signs";
}

@using (Html.BeginForm())
{
    <!-- Start Hidden form -->
    @Html.HiddenFor(m => m.EventCommand)
    @Html.HiddenFor(m => m.EventArgument)
    @Html.HiddenFor(m => m.Mode)
    @Html.HiddenFor(m => m.Schedule.Id)
    @Html.HiddenFor(m => m.Schedule.Name)
    for (int i = 0; i < Model.SignsForSchedule.Count; i++)
    {
        @Html.HiddenFor(model => Model.SignsForSchedule[i].Id)
        @Html.HiddenFor(model => Model.SignsForSchedule[i].Width)
        @Html.HiddenFor(model => Model.SignsForSchedule[i].Height)
        @Html.HiddenFor(model => Model.SignsForSchedule[i].Model)
    }
    for (int i = 0; i < Model.StoresForSchedule.Count; i++)
    {
        @Html.HiddenFor(model => Model.StoresForSchedule[i].Id)
        @Html.HiddenFor(model => Model.StoresForSchedule[i].IPAddress)
        @Html.HiddenFor(model => Model.StoresForSchedule[i].SubMask)
        @Html.HiddenFor(model => Model.StoresForSchedule[i].Port)
        @Html.HiddenFor(model => Model.StoresForSchedule[i].StoreName)
        @Html.HiddenFor(model => Model.StoresForSchedule[i].StoreId)
    }
   <!-- End Hidden form-->

    <div class="row">
        <div class="col-sm-12">
            @if (Model.DisplayMessage.Length>0)
            {
                <div class="alert alert-danger alert-dismissable" role="alert">
                    <button type="button" class="close" data-dissmiss="alert">
                        <span aria-hidden="true">&times</span>

                        <span class="sr-only">Close</span>
                    </button>
                    @Html.DisplayFor(m => m.DisplayMessage)
                    @Html.DisplayFor(m => m.DebugMessage)
                </div>
            }
        </div>
    </div>


    <div class="table-responsive">
        <table class="table table-condensed table-bordered table-striped table-hover">
            <thead>
                <tr>
                    <th>Image</th>
                </tr>
            </thead>
            <tbody>
                @Html.EditorFor(model => model.AllImagesInSchedule)
            </tbody>
        </table>

    </div>
    <div class="row">
        <div class="col-sm-12">
            <button type="submit" name="operation" class="btn btn-primary" id="btnSave">
                <i class="glyphicon glyphicon-floppy-disk"></i>&nbsp;Create & Send
            </button>
            <a href="@Url.Action("Resend", "SendToSign", new { scheduleId=Model.Schedule.Id, scheduleName=Model.Schedule.Name })" class="btn btn-primary">
                <i class="glyphicon glyphicon-repeat"></i>&nbsp;Resend
            </a>
            <a href="@Url.Action("Index", "Schedules")" class="btn btn-primary">
                <i class="glyphicon glyphicon-remove-circle"></i>&nbsp;Cancel
            </a>
        </div>
    </div>



}