nightowlsigns/Controllers/ImageController.cs
using ImageStorage;
using nightowlsign.data.Models.Image;
using nightowlsign.Models;
using System.Collections.Generic;
using System.Diagnostics.Tracing;
using System.Web;
using System.Web.Mvc;

namespace nightowlsign.Controllers
{
        
    public class ImageController : Controller
    {
        private readonly IImageViewModel _imageViewModel;

        public ImageController(IImageViewModel imageViewModel)
        {
            _imageViewModel = imageViewModel;
        }

        [AllowAnonymous]
        public ActionResult Index(int? SignId)
        {

            _imageViewModel.SearchSignId = Helper.GetSetSignSize(SignId);
            _imageViewModel.HandleRequest();
            _imageViewModel.ImageToUpload.Status = false;

            return View(_imageViewModel);
        }
        [AllowAnonymous]
        public ActionResult Show(ImageViewModel imageViewModel, int? SignId)
        {
            _imageViewModel.SearchSignId = Helper.GetSetSignSize(imageViewModel.SearchSignId); 
            _imageViewModel.HandleRequest();
            return View("Index", _imageViewModel);
        }


        [HttpPost]
        [Authorize(Roles = "Admin,SuperUser")]
        public ActionResult Index(FormCollection formCollection, ImageViewModel iVm, int? signId)
        {
            iVm.SearchSignId = Helper.GetSetSignSize(signId); 
            iVm.IsValid = ModelState.IsValid;
            if (Request != null)
            {
                var files = HttpContext.Request.Files;
                for (int i = 0; i < files.Count; i++)
                {
                    iVm.File = files[i];
                    if (i == files.Count-1){iVm.LastImage = true;}
                    iVm.HandleRequest();
                }
             }
            iVm.HandleRequest();
            if (iVm.IsValid)
            {
                ModelState.Clear();
            }
            else
            {
                foreach (KeyValuePair<string, string> item in iVm.ValidationErrors)
                {
                    ModelState.AddModelError(item.Key, item.Value);
                }
            }
            return View(iVm);
        }
    }
}

nightowlsigns/Controllers/LoggingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using nightowlsign.data;

using nightowlsign.data.Interfaces;
using nightowlsign.data.Models.Logging;

namespace nightowlsign.Controllers
{
    public class LoggingsController : Controller
    {
        private readonly Inightowlsign_Entities _context;
        private readonly ILoggingManager _loggingManager;

        public LoggingsController(Inightowlsign_Entities context, ILoggingManager loggingManager)
        {
            _context = context;
            _loggingManager = loggingManager;
        }
        // GET: Loggings
        [Authorize(Roles = "Admin,SuperUser")]

        public ActionResult Index(string filter="")
        {
            
            return View(_loggingManager.GetLatest(filter));
        }

        [Authorize(Roles = "Admin,SuperUser")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Logging logging =_context.Loggings.Find(id);
            if (logging == null)
            {
                return HttpNotFound();
            }
            return View(logging);
        }

        // GET: Loggings/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Loggings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Subject,Description,DateStamp")] Logging logging)
        {
            if (ModelState.IsValid)
            {
                _context.Loggings.Add(logging);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(logging);
        }

        // GET: Loggings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Logging logging = _context.Loggings.Find(id);
            if (logging == null)
            {
                return HttpNotFound();
            }
            return View(logging);
        }

        // POST: Loggings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Subject,Description,DateStamp")] Logging logging)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(logging).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(logging);
        }

        // GET: Loggings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Logging logging = _context.Loggings.Find(id);
            if (logging == null)
            {
                return HttpNotFound();
            }
            return View(logging);
        }

        // POST: Loggings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Logging logging = _context.Loggings.Find(id);
            _context.Loggings.Remove(logging);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

nightowlsigns/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using nightowlsign.data.Models.Schedule;
using nightowlsign.Models;

namespace nightowlsign.Controllers
{
    public class SchedulesController : Controller
    {
        private readonly IScheduleViewModel _scheduleViewModel;
         public SchedulesController(IScheduleViewModel scheduleViewModel)
        {
            _scheduleViewModel = scheduleViewModel;
                 }
        // GET: 
        [Authorize(Roles = "Admin,SuperUser")]
        public ActionResult Index(int signId)
        {
            signId = Helper.GetSetSignSize(signId);

            _scheduleViewModel.SearchEntity.SignId = signId;
            _scheduleViewModel.HandleRequest();
            return View(_scheduleViewModel);
        }

        [Authorize(Roles = "Admin,SuperUser")]
        public ActionResult Show()
        {
             _scheduleViewModel.HandleRequest();
            return View(_scheduleViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,SuperUser")]
        public ActionResult Index(ScheduleViewModel svm)
        {
            svm.SearchEntity.SignId = Helper.GetSetSignSize(svm.SearchEntity.SignId);

            svm.IsValid = ModelState.IsValid;
            svm.HandleRequest();

            if (svm.IsValid)
            {
                ModelState.Clear();
            }
            else
            {
                foreach (var item in svm.ValidationErrors)
                {
                    ModelState.AddModelError(item.Key, item.Value);
                }
            }
            return View(svm);
        }
    }
}

nightowlsigns/Controllers/StoresController.cs
using System.Web.Mvc;
using nightowlsign.data.Models.Stores;

namespace nightowlsign.Controllers
{
    public class StoresController : Controller
    {
        private readonly IStoreViewModel _storeViewModel;

        public StoresController(IStoreViewModel storeViewModel)
        {
            _storeViewModel = storeViewModel;
        }

        // GET: 
       // [Authorize(Roles = "Admin,SuperUser")]
        public ActionResult Index()
        {
          //  _storeViewModel.EventCommand = "ListAsync";
            _storeViewModel.HandleRequest();
            return View(_storeViewModel);
        }

        [Authorize(Roles = "Admin,SuperUser")]
        public ActionResult show()
        {
            _storeViewModel.HandleRequest();
            return View(_storeViewModel);
        }

        [HttpPost]
        [Authorize(Roles="Admin,Superuser")]
        public ActionResult Resend(int Id, string Name)
        {
            var result = Json(new { ResetDone = _storeViewModel.ResetLastStatus(Id) });
            return result;
          //  return _storeViewModel.ResetLastStatus(Id);
        }
        [HttpPost]
        [Authorize(Roles = "Admin,SuperUser")]
        public ActionResult Index(StoreViewModel storeViewModel)
        {
            storeViewModel.IsValid = ModelState.IsValid;
            storeViewModel.HandleRequest();

            if (storeViewModel.IsValid)
            {
                ModelState.Clear();
            }
            else
            {
                foreach (var item in storeViewModel.ValidationErrors)
                {
                    ModelState.AddModelError(item.Key, item.Value);
                }
            }
            return View(storeViewModel);
        }
    }
}

nightowlsigns/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>
    <script src="https://use.fontawesome.com/8dd41a5f58.js"></script>
    @RenderSection("scripts", required: false)
    <!--usage-->
    @RenderSection("customCSS", required: false)
    <!--other-->

</head>
<body>
    <header>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="#" class="navbar-brand">
                        <img src="~/Content/images/nightowl.png" />
                    </a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @Html.Partial("_menu")
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="body-content">
            <section class="row">
                <div class="fixed-attachment">
                    @RenderBody()
                </div>
            </section>
        </div>
    </div>
<footer id="footer">
    <div>&copy; @DateTime.Now.Year - Night Owl Sign System @typeof(nightowlsign.MvcApplication).Assembly.GetName().Version</div>
</footer>
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/custom")
</body>
</html>

nightowlsigns/Views/Shared/_menu.cshtml
@if (User.IsInRole("SuperUser"))
{
                    <li>@Html.ActionLink("Home", "Index", "Stores")</li>
                    <li>@Html.ActionLink("Images", "Index", "Image")</li>
                    <li>@Html.ActionLink("Playlists", "Index", "Schedules", new { SignId = "0" }, null)</li>
                    <li>@Html.ActionLink("Log", "Index", "Loggings", new { filter = "Result" }, null)</li>
}
else if (User.IsInRole("Admin"))
{
                    <li>@Html.ActionLink("Home", "Index", "Stores")</li>
                    <li>@Html.ActionLink("Images", "Index", "Image")</li>
                    <li>@Html.ActionLink("Playlists", "Index", "Schedules", new { SignId = "0" }, null)</li>
}
else
{
                    <li>@Html.ActionLink("Home", "Index", "Stores")</li>
}